# To use:
#
#   $ micromamba env create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate quip-conda
#
name: quip-conda
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - gfortran
  - pkg-config
  - openblas
  # Python
  - numpy
  - scipy
  - matplotlib
  - pandas
  - ipython
  - ipykernel
  - pip
  - ase
  - sh
  - f90wrap
  # Testing
  - pytest
  - pytest-datadir
